Repository sophiemoustard/compani-outils, pull requests merged in 2021-07, with the labels that each got.

#63 fix ios icon
  .expo-shared/assets.json
  app.json
  assets/images/ios_icon.png
Labels: dev

#61 Stop infinite loop use authcontext in use effect
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/context/AuthContext.ts
  src/context/createAuthContext.tsx
Labels: dev

#64 Com 2215 - npm update
  environment.ts
  package-lock.json
  package.json
  src/api/Versions.ts
Labels: dependancies

#65 Com 2189
  app.json
  package-lock.json
  package.json
  src/components/TimeStampingCell/index.tsx
  src/components/modals/CameraAccessModal/index.tsx
  src/components/modals/CameraAccessModal/styles.ts
  src/components/modals/Modal/index.tsx
  src/core/data/constants.ts
  src/navigation/AppNavigation/index.tsx
  src/navigation/Home/index.tsx
  src/screens/timeStampings/ManualTimeStamping/index.tsx
  src/screens/timeStampings/ManualTimeStamping/styles.ts
  src/screens/timeStampings/QRCodeScanner/index.tsx
  src/screens/timeStampings/QRCodeScanner/styles.ts
  src/screens/timeStampings/TimeStampingProfile/index.tsx
  src/screens/timeStampings/TimeStampingProfile/styles.ts
Labels: dev

#66 COM-2237 redirect to staging url + fix removal of userid on logout
  __tests__/authentication.test.js
  environment.ts
  src/api/Authentication.ts
  src/api/Events.ts
  src/api/Users.ts
  src/context/AuthContext.ts
  src/core/helpers/asyncStorage.ts
Labels: dev

#67 Com 2189 2
  app.json
  package-lock.json
  package.json
  src/api/Events.ts
  src/components/ErrorCell/index.tsx
  src/components/ErrorCell/styles.ts
  src/components/ErrorMessage/index.tsx
  src/components/EventInfoCell/index.tsx
  src/components/EventInfoCell/styles.ts
  src/components/TimeStampingCell/index.tsx
  src/components/modals/CameraAccessModal/styles.ts
  src/core/data/constants.ts
  src/navigation/AppNavigation/index.tsx
  src/navigation/Home/index.tsx
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  src/screens/timeStamping/ManualTimeStamping/styles.ts
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/screens/timeStamping/QRCodeScanner/styles.ts
  src/screens/timeStamping/TimeStampingProfile/index.tsx
  src/screens/timeStamping/TimeStampingProfile/styles.ts
  src/screens/timeStampings/ManualTimeStamping/styles.ts
  src/screens/timeStampings/QRCodeScanner/index.tsx
  src/screens/timeStampings/QRCodeScanner/styles.ts
  src/styles/metrics.ts
  src/types/EventType.ts
Labels: dev

#69 COM-2237 fix when no environment variables
  environment.ts
Labels: bug, dev

#68 Com 2189 distortion
  src/screens/timeStamping/QRCodeScanner/index.tsx
Labels: dev

#73 COM-2189 - Fix Ulysse review
  src/screens/timeStamping/QRCodeScanner/index.tsx
Labels: dev

#74 mise a jour des versions
  app.json
Labels: dev

#76 Dev
  src/components/FeatherButton/index.tsx
  src/components/modals/UpdateAppModal/index.tsx
  src/screens/Authentication/index.tsx
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  src/screens/timeStamping/ManualTimeStamping/styles.ts
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/screens/timeStamping/QRCodeScanner/styles.ts
  src/styles/metrics.ts
Labels: master
