Repository sophiemoustard/compani-outils, pull requests merged in 2021-11, with the labels that each got.

#96 maj des versions - mep 03/11
  app.json
Labels: dev

#97 mep-03/11
  .github/pull_request_template.md
  .github/workflows/integration-tests.yml
  .github/workflows/ts-lint.yml
  app.json
  package-lock.json
  package.json
  src/components/TimeStampingCell/index.tsx
  src/screens/Profile/index.tsx
  src/types/EventType.ts
Labels: master

#98 COM-2490 - expo 43 update (npm update)
  .github/workflows/integration-tests.yml
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/components/TimeStampingCell/index.tsx
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  tsconfig.json
Labels: dev, dependancies

#99 Com 2468
  package-lock.json
  src/components/TimeStampingCell/index.tsx
  src/core/data/constants.ts
  src/core/helpers/dates.ts
  src/navigation/AppNavigation/index.tsx
  src/navigation/Home/index.tsx
  src/navigation/Home/styles.ts
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/EventEdition/styles.ts
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/screens/timeStamping/TimeStampingProfile/index.tsx
  src/styles/colors.ts
  src/styles/metrics.ts
  src/types/IconType.ts
  src/types/NavigationType.ts
Labels: dev

#100 Com 2470
  App/styles.ts
  package-lock.json
  package.json
  src/components/EventDateTime/index.tsx
  src/components/EventDateTime/styles.ts
  src/components/TimeStampingCell/index.tsx
  src/components/modals/UpdateAppModal/index.tsx
  src/core/data/constants.ts
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/EventEdition/styles.ts
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/styles/colors.ts
  src/styles/metrics.ts
  src/types/EventType.ts
Labels: dev

#102 Com 2470
  src/api/Events.ts
  src/api/Users.ts
  src/components/EventDateTime/index.tsx
  src/components/form/PrimaryButton/index.tsx
  src/components/modals/ExitModal/index.tsx
  src/core/helpers/dates.ts
  src/screens/ProfileEdition/index.tsx
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/EventEdition/styles.ts
  src/styles/metrics.ts
  src/types/EventType.ts
Labels: dev

#103 Com 2540 ou COM 2470 fix
  src/screens/timeStamping/EventEdition/index.tsx
Labels: bug, dev

#105 mep 22/11
  .github/workflows/integration-tests.yml
  App/styles.ts
  app.json
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/api/Events.ts
  src/api/Users.ts
  src/components/EventDateTime/index.tsx
  src/components/EventDateTime/styles.ts
  src/components/TimeStampingCell/index.tsx
  src/components/form/PrimaryButton/index.tsx
  src/components/modals/ExitModal/index.tsx
  src/components/modals/UpdateAppModal/index.tsx
  src/core/data/constants.ts
  src/core/helpers/dates.ts
  src/navigation/AppNavigation/index.tsx
  src/navigation/Home/index.tsx
  src/navigation/Home/styles.ts
  src/screens/ProfileEdition/index.tsx
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/EventEdition/styles.ts
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/screens/timeStamping/TimeStampingProfile/index.tsx
  src/styles/colors.ts
  src/styles/metrics.ts
  src/types/EventType.ts
  src/types/IconType.ts
  src/types/NavigationType.ts
  tsconfig.json
Labels: master

#106 Com 2534 - expo update (npm update)
  .eslintrc.js
  package-lock.json
  package.json
  src/components/TimeStampingCell/index.tsx
  src/screens/timeStamping/ManualTimeStamping/index.tsx
  tsconfig.json
Labels: dev, dependancies

#107 COM-2470 - Fix Romain's reviews
  src/components/PasswordForm/index.tsx
  src/components/modals/CameraAccessModal/index.tsx
  src/components/modals/ExitModal/styles.ts
  src/components/modals/ForgotPasswordModal/index.tsx
  src/core/helpers/dates.ts
  src/screens/ForgotPassword/index.tsx
  src/screens/ProfileEdition/index.tsx
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/TimeStampingProfile/index.tsx
Labels: dev

#109 COM-2470 - Fix css
  src/components/modals/ExitModal/styles.ts
Labels: dev

#108 Com 2541
  App/styles.ts
  src/components/EventDateTimeEdition/index.tsx
  src/components/EventDateTimeEdition/styles.ts
  src/components/TimeStampingCell/index.tsx
  src/components/modals/UpdateAppModal/index.tsx
  src/core/data/constants.ts
  src/screens/timeStamping/EventEdition/index.tsx
  src/screens/timeStamping/EventEdition/styles.ts
  src/screens/timeStamping/QRCodeScanner/index.tsx
  src/styles/metrics.ts
Labels: dev
