Repository sophiemoustard/compani-outils, pull requests merged in 2022-03, with the labels that each got.

#156 MEP-04/03
  app.json
Labels: dev

#162 COM-2741 - Fix on large screen
  src/components/EventCell/index.tsx
  src/components/EventCell/styles.ts
  src/screens/timeStamping/QRCodeScanner/styles.ts
Labels: dev

#164 Fix css after rebase in COM-2728
  src/components/EventCell/index.tsx
  src/components/EventCell/styles.ts
Labels: dev

#163 Com 2725
  src/api/Helpers.ts
  src/components/PersonEditionModal/index.tsx
  src/components/PersonSelect/index.tsx
  src/components/PersonSelect/styles.ts
  src/core/helpers/auxiliaries.ts
  src/core/helpers/helpers.ts
  src/screens/CustomerProfile/index.tsx
  src/screens/CustomerProfile/style.ts
  src/screens/timeStamping/EventEdition/index.tsx
  src/types/HelperType.ts
  src/types/UserType.ts
Labels: dev

#171 COM-2725 fix bug on customer profile
  src/components/PersonEditionModal/index.tsx
  src/types/UserType.ts
Labels: bug, dev

#172 MEP-2103 change version code
  app.json
Labels: dev

#173 MEP 1.8.1
  app.json
  src/components/EventCell/index.tsx
  src/components/EventCell/styles.ts
  src/components/PersonEditionModal/index.tsx
  src/styles/metrics.ts
  src/types/UserType.ts
Labels: master
